# Fichier : netlify.toml

[build]
  # Indique à Netlify que vos fichiers de site (index.html, etc.) sont à la racine
  publish = "."
  # Indique à Netlify où trouver vos fonctions à déployer
  functions = "netlify/functions"

[functions]
  # Force l'inclusion du dossier _data avec les fonctions
  included_files = ["netlify/functions/_data/**"]

# Redirection pour que /.netlify/functions/ soit accessible
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
