# Fichier : netlify.toml

[functions]
  # Indique à Netlify où se trouvent vos fonctions
  directory = "netlify/functions/"

# Cette règle s'applique à TOUTES les fonctions
[[functions."*"]]
  # Force l'inclusion du dossier "private" et de tout son contenu
  included_files = ["private/**"]