# Fichier : netlify.toml

[functions]
  # Indique à Netlify où se trouvent vos fonctions
  directory = "netlify/functions/"

  # Cette ligne force l'inclusion du dossier _data et de tout son contenu
  # avec les fonctions lors du déploiement.
  included_files = ["netlify/functions/_data/**"]
