# netlify.toml (version corrigée et complète)

[build]
  publish = "."

[functions]
  directory = "netlify/functions"

# On met à jour les en-têtes de sécurité pour autoriser les ressources externes
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://unpkg.com https://fonts.googleapis.com https://cdn.jsdelivr.net; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com data:; connect-src 'self';"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"