# This tells Netlify how to build your main site
[build]
  command = "npm run build"
  publish = "."

# This new section tells Netlify where to find your functions
[functions]
  directory = "netlify/functions"

# This section adds the necessary security headers to allow reCAPTCHA to work
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      script-src 'self' 'unsafe-inline' https://www.google.com https://www.gstatic.com https://cdn.jsdelivr.net;
      style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://code.ionicframework.com;
      frame-src 'self' https://www.google.com https://www.gstatic.com;
      font-src 'self' https://code.ionicframework.com data:;
    """